stages:
    - build

variables:
    CARGO_TERM_COLOR: always

workflow:
    rules:
        - if: $CI_COMMIT_BRANCH

build_linux:
    stage: build
    image: rust:1.95.0-trixie

    before_script:
        - apt-get update
        - |
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            pkg-config \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libwayland-dev \
            libx11-dev \
            build-essential
        - rustup target add x86_64-unknown-linux-gnu
    
    script:
        - cargo build --release --target x86_64-unknown-linux-gnu
        - mkdir -p artifacts/linux
        - cp target/x86_64-unknown-linux-gnu/release/animoe artifacts/linux/animoe_x86_64-unknown-linux-gnu
    
    artifacts:
        name: "linux-build-$CI_COMMIT_SHORT_SHA"
        paths:
            - artifacts/linux/
        expire_in: 3 days

build_windows:
    stage: build
    
    tags:
        - windows

    script:
        - cargo build --release
        - mkdir -p artifacts/windows
        - cp target/release/animoe.exe artifacts/windows/animoe_x86_64-pc-windows-msvc.exe

    artifacts:
        name: "windows-build-$CI_COMMIT_SHORT_SHA"
        paths:
        - artifacts/windows/
        expire_in: 3 days
