name: Build (Cross Platfrom)

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build-linux:
    name: Build (Linux x86_64)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      
      - name: Install Required Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfontconfig1-dev
      
      - name: Cargo Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: animoe-x86_64-unknown-linux-gnu
          path: target/release/animoe
