name: Build (Cross Platfrom)

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build-linux:
    name: Build (Linux x86_64)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-cache
      
      - name: Install Required Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          pkg-config \
          libfontconfig1-dev \
          libxcb1-dev \
          libxkbcommon-dev \
          libxkbcommon-x11-dev \
          libx11-dev \
          libxrandr-dev \
          libxi-dev \
          libxcursor-dev \
          libgl1-mesa-dev

      - name: Add required secrets to repo
        run: |
          echo "${{ secrets.ANIMOE_CREDS }}" | base64 --decode > ${{ github.workspace }}/src/utils/constants.rs
      
      - name: Cargo Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: animoe-x86_64-unknown-linux-gnu
          path: ${{ github.workspace }}/target/release/animoe

  build-windows:
    name: Build (Windows x86_64)
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
  
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-cache-windows
  
      - name: Add required secrets to repo
        run: |
          [System.Convert]::FromBase64String("${{ secrets.ANIMOE_CREDS }}") | Set-Content -Path "${{ github.workspace }}\src\utils\constants.rs" -AsByteStream
  
      - name: Cargo Build
        run: cargo build --release
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: animoe-x86_64-pc-windows-msvc
          path: ${{ github.workspace }}\target\release\animoe.exe